# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminManagerProfiles.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 420)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 541, 381))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_managerProfiles = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_managerProfiles.setFont(font)
        self.label_managerProfiles.setAlignment(QtCore.Qt.AlignCenter)
        self.label_managerProfiles.setObjectName("label_managerProfiles")
        self.verticalLayout.addWidget(self.label_managerProfiles)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_search = QtWidgets.QLabel(self.layoutWidget)
        self.label_search.setObjectName("label_search")
        self.horizontalLayout.addWidget(self.label_search)
        self.line_searchBar = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_searchBar.setObjectName("line_searchBar")
        self.horizontalLayout.addWidget(self.line_searchBar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tbl_managerProfiles = QtWidgets.QTableView(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_managerProfiles.sizePolicy().hasHeightForWidth())
        self.tbl_managerProfiles.setSizePolicy(sizePolicy)
        self.tbl_managerProfiles.setObjectName("tbl_managerProfiles")
        self.verticalLayout.addWidget(self.tbl_managerProfiles)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_registerManager = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_registerManager.setObjectName("btn_registerManager")
        self.horizontalLayout_2.addWidget(self.btn_registerManager)
        self.btn_removeManager = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_removeManager.setObjectName("btn_removeManager")
        self.horizontalLayout_2.addWidget(self.btn_removeManager)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem1)
        self.btn_backToDashboard = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_backToDashboard.setObjectName("btn_backToDashboard")
        self.verticalLayout.addWidget(self.btn_backToDashboard)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_managerProfiles.setText(_translate("MainWindow", "Manager Profiles"))
        self.label_search.setText(_translate("MainWindow", "Search:"))
        self.btn_registerManager.setText(_translate("MainWindow", "Register New Manager"))
        self.btn_removeManager.setText(_translate("MainWindow", "Remove Selected Manager"))
        self.btn_backToDashboard.setText(_translate("MainWindow", "Back to Dashboard"))
