# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminUpdateLog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 781, 561))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_recentUpdates = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_recentUpdates.setFont(font)
        self.lbl_recentUpdates.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_recentUpdates.setObjectName("lbl_recentUpdates")
        self.verticalLayout.addWidget(self.lbl_recentUpdates)
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ln_searchBar = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_searchBar.sizePolicy().hasHeightForWidth())
        self.ln_searchBar.setSizePolicy(sizePolicy)
        self.ln_searchBar.setMinimumSize(QtCore.QSize(220, 0))
        self.ln_searchBar.setObjectName("ln_searchBar")
        self.horizontalLayout.addWidget(self.ln_searchBar)
        spacerItem1 = QtWidgets.QSpacerItem(238, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lbl_sort = QtWidgets.QLabel(self.widget)
        self.lbl_sort.setObjectName("lbl_sort")
        self.horizontalLayout.addWidget(self.lbl_sort)
        self.combo_sort = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_sort.sizePolicy().hasHeightForWidth())
        self.combo_sort.setSizePolicy(sizePolicy)
        self.combo_sort.setObjectName("combo_sort")
        self.combo_sort.addItem("")
        self.combo_sort.addItem("")
        self.combo_sort.addItem("")
        self.horizontalLayout.addWidget(self.combo_sort)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tbl_updateLog = QtWidgets.QTableView(self.widget)
        self.tbl_updateLog.setObjectName("tbl_updateLog")
        self.verticalLayout.addWidget(self.tbl_updateLog)
        self.btn_backToDashboard = QtWidgets.QPushButton(self.widget)
        self.btn_backToDashboard.setObjectName("btn_backToDashboard")
        self.verticalLayout.addWidget(self.btn_backToDashboard)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Update Log"))
        self.lbl_recentUpdates.setText(_translate("MainWindow", "Update Log"))
        self.label.setText(_translate("MainWindow", "Search:"))
        self.lbl_sort.setText(_translate("MainWindow", "Sort by:"))
        self.combo_sort.setItemText(0, _translate("MainWindow", "Select Sort"))
        self.combo_sort.setItemText(1, _translate("MainWindow", "Most Recent"))
        self.combo_sort.setItemText(2, _translate("MainWindow", "Action"))
        self.btn_backToDashboard.setText(_translate("MainWindow", "Back to Dashboard"))
