# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'managerApplicantLog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 461))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vLayout_pendingApplications = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vLayout_pendingApplications.setContentsMargins(0, 0, 0, 0)
        self.vLayout_pendingApplications.setObjectName("vLayout_pendingApplications")
        self.label_applicantLog = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_applicantLog.setFont(font)
        self.label_applicantLog.setAlignment(QtCore.Qt.AlignCenter)
        self.label_applicantLog.setObjectName("label_applicantLog")
        self.vLayout_pendingApplications.addWidget(self.label_applicantLog)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_search = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_search.setObjectName("label_search")
        self.horizontalLayout.addWidget(self.label_search)
        self.line_searchBar = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_searchBar.setObjectName("line_searchBar")
        self.horizontalLayout.addWidget(self.line_searchBar)
        self.vLayout_pendingApplications.addLayout(self.horizontalLayout)
        self.tbl_applicantLog = QtWidgets.QTableView(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(10)
        self.tbl_applicantLog.setFont(font)
        self.tbl_applicantLog.setObjectName("tbl_applicantLog")
        self.vLayout_pendingApplications.addWidget(self.tbl_applicantLog)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.vLayout_pendingApplications.addItem(spacerItem1)
        self.btn_delApplicant = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_delApplicant.setObjectName("btn_delApplicant")
        self.vLayout_pendingApplications.addWidget(self.btn_delApplicant)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.vLayout_pendingApplications.addItem(spacerItem2)
        self.btn_backToDashboard = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_backToDashboard.setObjectName("btn_backToDashboard")
        self.vLayout_pendingApplications.addWidget(self.btn_backToDashboard)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pending Applications"))
        self.label_applicantLog.setText(_translate("MainWindow", "Applicant Log"))
        self.label_search.setText(_translate("MainWindow", "Search:"))
        self.btn_delApplicant.setText(_translate("MainWindow", "Delete Applicant"))
        self.btn_backToDashboard.setText(_translate("MainWindow", "Back to Dashboard"))
